Создаём базу
htmlacademy-php/581221-doingsdone-12 pull request #7
Opened 2020-07-31 09:50 UTC by artemevskih

2020-08-03 04:42 UTC, nkolosov requested changes

2020-08-03 04:42 UTC, nkolosov commented on schema.sql
> +/*CREATE DATABASE doingsdone
Почему закомментированно? Это тоже нужно

2020-08-03 04:42 UTC, nkolosov commented on schema.sql
> +  email VARCHAR(128) NOT NULL UNIQUE,
email может быть длиннее 128 символов

2020-08-03 04:42 UTC, nkolosov commented on schema.sql
> +  user_id INT NOT NULL,
На поля для связи с другими таблицами нужно повесить FOREIGN KEY

2020-08-04 13:45 UTC, artemevskih commented on schema.sql
> +/*CREATE DATABASE doingsdone
Выполнял код частями. Сначала базу создал, проверил, потом таблицы.

2020-08-05 05:13 UTC, nkolosov requested changes

2020-08-05 05:13 UTC, nkolosov commented on schema.sql
> +
Здесь нужно добавить `USE` чтобы можно было просто скопировать файл и выполнить его в БД

2020-08-05 05:13 UTC, nkolosov commented on schema.sql
> +  user_id INT FOREIGN KEY NOT NULL,
Данная конструкция не работает, FOREIGN KEY указывается не так.

2020-08-07 04:36 UTC, merged